language: objective-c

env:
    - PROJECT_SCHEME=Simian
    - PROJECT_SCHEME=ROADAttributesCodeGenerator
    - PROJECT_SCHEME=libObjCAttr
    - PROJECT_SCHEME=libObjCAttrMac

before_script:
    - sudo easy_install cpp-coveralls
    - chmod +x ./script_simian.sh
    - chmod +x ./script_general.sh
    - chmod +x ./coveralls.rb

script:
    - if [[ $PROJECT_SCHEME == Simian ]]; then ./script_simian.sh; else ./script_general.sh; fi

after_success:
    - if [[ $PROJECT_SCHEME != Simian && $PROJECT_SCHEME != ROADAttributesCodeGenerator ]]; then ./coveralls.rb --extension m --exclude-folder ROADGeneratedAttributes; fi

notifications:
  email:
    - Nikita_Leonov@epam.com
    - Yuru_Taustahuzau@epam.com